name: Deploy para páginas do GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Corrigido "rush-on" para "runs-on"

    steps:
      # 1. Verifica o repositório
      - name: Checar o repositório
        uses: actions/checkout@v3  # Correto

      # 2. Configurar o GitHub Pages
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3  # Correto

      # 3. Construir o projeto (se necessário)
      - name: Construir os arquivos para deploy
        run: |
          # Dependendo do seu projeto, execute os comandos para gerar os arquivos estáticos, como:
          # npm install
          # npm run build
          # ou algo específico para o seu projeto

      # 4. Publicar no GitHub Pages
      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v1
